/*
 * This file is part of picam.
 *
 * picam is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * picam is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with picam.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright 2016 Caprica Software Limited.
 */

package uk.co.caprica.picam.bindings;

public final class MmalParameters {

    private static final int MMAL_PARAMETER_GROUP_COMMON = 0 << 16;
    private static final int MMAL_PARAMETER_GROUP_CAMERA = 1 << 16;
    private static final int MMAL_PARAMETER_GROUP_VIDEO = 2 << 16;
    private static final int MMAL_PARAMETER_GROUP_AUDIO = 3 << 16;
    private static final int MMAL_PARAMETER_GROUP_CLOCK = 4 << 16;
    private static final int MMAL_PARAMETER_GROUP_MIRACAST = 5 << 16;

    // FIXME can any more of these be used?
    public static final int MMAL_PARAMETER_THUMBNAIL_CONFIGURATION = MMAL_PARAMETER_GROUP_CAMERA + 0;
    public static final int MMAL_PARAMETER_CAPTURE_QUALITY = MMAL_PARAMETER_GROUP_CAMERA + 1;
    public static final int MMAL_PARAMETER_ROTATION = MMAL_PARAMETER_GROUP_CAMERA + 2;
    public static final int MMAL_PARAMETER_EXIF_DISABLE = MMAL_PARAMETER_GROUP_CAMERA + 3;
    public static final int MMAL_PARAMETER_EXIF = MMAL_PARAMETER_GROUP_CAMERA + 4;
    public static final int MMAL_PARAMETER_AWB_MODE = MMAL_PARAMETER_GROUP_CAMERA + 5;
    public static final int MMAL_PARAMETER_IMAGE_EFFECT = MMAL_PARAMETER_GROUP_CAMERA + 6;
    public static final int MMAL_PARAMETER_COLOUR_EFFECT = MMAL_PARAMETER_GROUP_CAMERA + 7;
    public static final int MMAL_PARAMETER_FLICKER_AVOID = MMAL_PARAMETER_GROUP_CAMERA + 8;
    public static final int MMAL_PARAMETER_FLASH = MMAL_PARAMETER_GROUP_CAMERA + 9;
    public static final int MMAL_PARAMETER_REDEYE = MMAL_PARAMETER_GROUP_CAMERA + 10;
    public static final int MMAL_PARAMETER_FOCUS = MMAL_PARAMETER_GROUP_CAMERA + 11;
    public static final int MMAL_PARAMETER_FOCAL_LENGTHS = MMAL_PARAMETER_GROUP_CAMERA + 12;
    public static final int MMAL_PARAMETER_EXPOSURE_COMP = MMAL_PARAMETER_GROUP_CAMERA + 13;
    public static final int MMAL_PARAMETER_ZOOM = MMAL_PARAMETER_GROUP_CAMERA + 14;
    public static final int MMAL_PARAMETER_MIRROR = MMAL_PARAMETER_GROUP_CAMERA + 15;
    public static final int MMAL_PARAMETER_CAMERA_NUM = MMAL_PARAMETER_GROUP_CAMERA + 16;
    public static final int MMAL_PARAMETER_CAPTURE = MMAL_PARAMETER_GROUP_CAMERA + 17;
    public static final int MMAL_PARAMETER_EXPOSURE_MODE = MMAL_PARAMETER_GROUP_CAMERA + 18;
    public static final int MMAL_PARAMETER_EXP_METERING_MODE = MMAL_PARAMETER_GROUP_CAMERA + 19;
    public static final int MMAL_PARAMETER_FOCUS_STATUS = MMAL_PARAMETER_GROUP_CAMERA + 20;
    public static final int MMAL_PARAMETER_CAMERA_CONFIG = MMAL_PARAMETER_GROUP_CAMERA + 21;
    public static final int MMAL_PARAMETER_CAPTURE_STATUS = MMAL_PARAMETER_GROUP_CAMERA + 22;
    public static final int MMAL_PARAMETER_FACE_TRACK = MMAL_PARAMETER_GROUP_CAMERA + 23;
    public static final int MMAL_PARAMETER_DRAW_BOX_FACES_AND_FOCUS = MMAL_PARAMETER_GROUP_CAMERA + 24;
    public static final int MMAL_PARAMETER_JPEG_Q_FACTOR = MMAL_PARAMETER_GROUP_CAMERA + 25;
    public static final int MMAL_PARAMETER_FRAME_RATE = MMAL_PARAMETER_GROUP_CAMERA + 26;
    public static final int MMAL_PARAMETER_USE_STC = MMAL_PARAMETER_GROUP_CAMERA + 27;
    public static final int MMAL_PARAMETER_CAMERA_INFO = MMAL_PARAMETER_GROUP_CAMERA + 28;
    public static final int MMAL_PARAMETER_VIDEO_STABILISATION = MMAL_PARAMETER_GROUP_CAMERA + 29;
    public static final int MMAL_PARAMETER_FACE_TRACK_RESULTS = MMAL_PARAMETER_GROUP_CAMERA + 30;
    public static final int MMAL_PARAMETER_ENABLE_RAW_CAPTURE = MMAL_PARAMETER_GROUP_CAMERA + 31;
    public static final int MMAL_PARAMETER_DPF_FILE = MMAL_PARAMETER_GROUP_CAMERA + 32;
    public static final int MMAL_PARAMETER_ENABLE_DPF_FILE = MMAL_PARAMETER_GROUP_CAMERA + 33;
    public static final int MMAL_PARAMETER_DPF_FAIL_IS_FATAL = MMAL_PARAMETER_GROUP_CAMERA + 34;
    public static final int MMAL_PARAMETER_CAPTURE_MODE = MMAL_PARAMETER_GROUP_CAMERA + 35;
    public static final int MMAL_PARAMETER_FOCUS_REGIONS = MMAL_PARAMETER_GROUP_CAMERA + 36;
    public static final int MMAL_PARAMETER_INPUT_CROP = MMAL_PARAMETER_GROUP_CAMERA + 37;
    public static final int MMAL_PARAMETER_SENSOR_INFORMATION = MMAL_PARAMETER_GROUP_CAMERA + 38;
    public static final int MMAL_PARAMETER_FLASH_SELECT = MMAL_PARAMETER_GROUP_CAMERA + 39;
    public static final int MMAL_PARAMETER_FIELD_OF_VIEW = MMAL_PARAMETER_GROUP_CAMERA + 40;
    public static final int MMAL_PARAMETER_HIGH_DYNAMIC_RANGE = MMAL_PARAMETER_GROUP_CAMERA + 41;
    public static final int MMAL_PARAMETER_DYNAMIC_RANGE_COMPRESSION = MMAL_PARAMETER_GROUP_CAMERA + 42;
    public static final int MMAL_PARAMETER_ALGORITHM_CONTROL = MMAL_PARAMETER_GROUP_CAMERA + 43;
    public static final int MMAL_PARAMETER_SHARPNESS = MMAL_PARAMETER_GROUP_CAMERA + 44;
    public static final int MMAL_PARAMETER_CONTRAST = MMAL_PARAMETER_GROUP_CAMERA + 45;
    public static final int MMAL_PARAMETER_BRIGHTNESS = MMAL_PARAMETER_GROUP_CAMERA + 46;
    public static final int MMAL_PARAMETER_SATURATION = MMAL_PARAMETER_GROUP_CAMERA + 47;
    public static final int MMAL_PARAMETER_ISO = MMAL_PARAMETER_GROUP_CAMERA + 48;
    public static final int MMAL_PARAMETER_ANTISHAKE = MMAL_PARAMETER_GROUP_CAMERA + 49;
    public static final int MMAL_PARAMETER_IMAGE_EFFECT_PARAMETERS = MMAL_PARAMETER_GROUP_CAMERA + 50;
    public static final int MMAL_PARAMETER_CAMERA_BURST_CAPTURE = MMAL_PARAMETER_GROUP_CAMERA + 51;
    public static final int MMAL_PARAMETER_CAMERA_MIN_ISO = MMAL_PARAMETER_GROUP_CAMERA + 52;
    public static final int MMAL_PARAMETER_CAMERA_USE_CASE = MMAL_PARAMETER_GROUP_CAMERA + 53;
    public static final int MMAL_PARAMETER_CAPTURE_STATS_PASS = MMAL_PARAMETER_GROUP_CAMERA + 54;
    public static final int MMAL_PARAMETER_CAMERA_CUSTOM_SENSOR_CONFIG = MMAL_PARAMETER_GROUP_CAMERA + 55;
    public static final int MMAL_PARAMETER_ENABLE_REGISTER_FILE = MMAL_PARAMETER_GROUP_CAMERA + 56;
    public static final int MMAL_PARAMETER_REGISTER_FAIL_IS_FATAL = MMAL_PARAMETER_GROUP_CAMERA + 57;
    public static final int MMAL_PARAMETER_CONFIGFILE_REGISTERS = MMAL_PARAMETER_GROUP_CAMERA + 58;
    public static final int MMAL_PARAMETER_CONFIGFILE_CHUNK_REGISTERS = MMAL_PARAMETER_GROUP_CAMERA + 59;
    public static final int MMAL_PARAMETER_JPEG_ATTACH_LOG = MMAL_PARAMETER_GROUP_CAMERA + 60;
    public static final int MMAL_PARAMETER_ZERO_SHUTTER_LAG = MMAL_PARAMETER_GROUP_CAMERA + 61;
    public static final int MMAL_PARAMETER_FPS_RANGE = MMAL_PARAMETER_GROUP_CAMERA + 62;
    public static final int MMAL_PARAMETER_CAPTURE_EXPOSURE_COMP = MMAL_PARAMETER_GROUP_CAMERA + 63;
    public static final int MMAL_PARAMETER_SW_SHARPEN_DISABLE = MMAL_PARAMETER_GROUP_CAMERA + 64;
    public static final int MMAL_PARAMETER_FLASH_REQUIRED = MMAL_PARAMETER_GROUP_CAMERA + 65;
    public static final int MMAL_PARAMETER_SW_SATURATION_DISABLE = MMAL_PARAMETER_GROUP_CAMERA + 66;
    public static final int MMAL_PARAMETER_SHUTTER_SPEED = MMAL_PARAMETER_GROUP_CAMERA + 67;
    public static final int MMAL_PARAMETER_CUSTOM_AWB_GAINS = MMAL_PARAMETER_GROUP_CAMERA + 68;
    public static final int MMAL_PARAMETER_CAMERA_SETTINGS = MMAL_PARAMETER_GROUP_CAMERA + 69;
    public static final int MMAL_PARAMETER_PRIVACY_INDICATOR = MMAL_PARAMETER_GROUP_CAMERA + 70;
    public static final int MMAL_PARAMETER_VIDEO_DENOISE = MMAL_PARAMETER_GROUP_CAMERA + 71;
    public static final int MMAL_PARAMETER_STILLS_DENOISE = MMAL_PARAMETER_GROUP_CAMERA + 72;
    public static final int MMAL_PARAMETER_ANNOTATE = MMAL_PARAMETER_GROUP_CAMERA + 73;
    public static final int MMAL_PARAMETER_STEREOSCOPIC_MODE = MMAL_PARAMETER_GROUP_CAMERA + 74;
    public static final int MMAL_PARAMETER_CAMERA_INTERFACE = MMAL_PARAMETER_GROUP_CAMERA + 75;
    public static final int MMAL_PARAMETER_CAMERA_CLOCKING_MODE = MMAL_PARAMETER_GROUP_CAMERA + 76;
    public static final int MMAL_PARAMETER_CAMERA_RX_CONFIG = MMAL_PARAMETER_GROUP_CAMERA + 77;
    public static final int MMAL_PARAMETER_CAMERA_RX_TIMING = MMAL_PARAMETER_GROUP_CAMERA + 78;
    public static final int MMAL_PARAMETER_DPF_CONFIG = MMAL_PARAMETER_GROUP_CAMERA + 79;
    public static final int MMAL_PARAMETER_JPEG_RESTART_INTERVAL = MMAL_PARAMETER_GROUP_CAMERA + 80;
    public static final int MMAL_PARAMETER_CAMERA_ISP_BLOCK_OVERRIDE = MMAL_PARAMETER_GROUP_CAMERA + 81;
    public static final int MMAL_PARAMETER_LENS_SHADING_OVERRIDE = MMAL_PARAMETER_GROUP_CAMERA + 82;
}
